/*
nomes - CHAR E VARCHAR
numeros - FLOAT E INT
documentos - BLOB
texto extenso - TEXT
*/

/* 
COMPARANDO CHAR e VARCHAR 

1 CARACTER = 1 BYTE

CHAR(10) 
JOÃO = 10BYTES

VARCHAR(10)
JOÃO = 4 BYTES


CONCLUSÃO 

O VARCHAR VARIA SEU TAMANHO SENDO MENOS PERFORMATICO 

UTILIZAR CHAR QUANDO: O NÚMERO DE CARACTERES DA COLUNA NUNCA FOR VARIANTE
*/


/*
COMPARANDO ENUM E NUMÉROCOS

ENUN = ENUMERAÇÃO

LIMITAR O NUMERO EM UMA COLUNA E APLICAR UMA COMBOBOX COM DADOS PRÉ DETERMINADOS

CONJUNTO DELIMITADO DE VALORES

O ENUM ESTA PRESENTE APENAS NO MSQ 


TIPOS NUMERICOAS


FLOAT = NÚMEROS REAIS

1343,877507 = MAIOR PRECISÃO

1354253,89 = MENOR PRECISÃO

FLOAT(TOTAL,VIRGULA)

FLOAT(10,2) LEMBRANDO QUE O 10 E NUMERO TOTAL, NÃO AVERA 2 APÓS A VIRGULA


INT = NÚMERO INTEIRO

10
500
8000

MÁXIMO DE 11 DIGITOS

NUMEROS QUE NÃO NECESSITAM DE CÁLCULOS PODEM SER TIPADOS COM VARCHAR!
*/