/* MODELAGEM BÁSICA - 

ENTIDADE = TABELA 
CAMPOS = ATRIBUTOS

*/

CLIENTE

NOME - CARACTER(30)
CPF - NUMERICO(11)
EMAIL - CARACTER(30)
TELEFONE - CARACTER(30)
ENDERECO - CARACTER(100)
SEXO - CARACTER(1)

/* PROCESSOS DE MODELAGEM */

/* FASE 01 E FASE 02 - ADM DE DADOS */

MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM

/* FASE 03 - DBA / AD */

MODELAGEM FÍSICA - SCRIPTS DE BANCO 

/* INICIANDO A MODELAGEM FÍSICA */

/* CRIANDO O BANCO DE DADOS */

CREATE DATABASE EXEMPLO

CREATE DATABASE PROJETO;

/* CONECTANDO-SE AO BANCO */

USE PROJETO;

/* CRIANDO A TABLA DO CLIENTES */

CREATE TABLE CLIENTE (
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
);

/* VERIFICANDO AS TABELAS DO BANCO DE DADOS */

SHOW TABLES;

/* DESCOBRINDO COMO É A ESTRUTURA DE UMA TABELA */

DESC CLIENTE;

/* SINTAXE BÁSICA DE INSERÇÃO - INSERT INTO TABELA... */

/* FORMA 01 - OMITINDO AS COLUNAS */

INSERT INTO CLIENTE VALUES('JHONATAN','M','JHONY@GMAIL.COM',988633441,'16999333990','RUA MAIA - RIBEIRAO PRETO - SP');

/* FORMA 02 - DESCREVENDO AS COLUNAS */

INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('THIAGO','M','RUA TACO - RIBEIRAO PRETO - SP','16999333944', 988633455);

/* FORMA 03 - INSERT COMPACTO - SOMENTE MYSQL */

INSERT INTO CLIENTE VALUE('WELL','M','WELL@GMAIL.COM',228633441,'16999733990','RUA MARIO - RIBEIRAO PRETO - SP'),
						 ('DANIEL','M','DANI@GMAIL.COM',988563441,'16999833990','RUA EUCLIDES - RIBEIRAO PRETO - SP');
						 
						 
INSERT INTO CLIENTE VALUES('LARISSA','F','LARI@GMAIL.COM',98863344112,'16999339490','RUA MAIA - RIBEIRAO PRETO - SP');

/* O COMANDO SELECT - SELEÇÃO, 'PROJEÇÃO' E JUNÇÃO */

SELECT NOW();

SELECT NOW() AS DATA_HORA;

SELECT NOW() AS DATA_HORA, 'JHONATAN' AS ALUNO;

SELECT 'JHONATAN';

SELECT 'BANCO DE DADOS';

/* ALIAS DE COLUNAS */

SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;

SELECT EMAIL, SEXO, ENDERECO, NOME FROM CLIENTE;

SELECT EMAIL, SEXO, ENDERECO, NOME, NOW() AS DATA_HORA FROM CLIENTE;

/* APENAS PARA FINS ACADEMICOS */

SELECT * FROM CLIENTE;






