/* MODELAGEM BÁSICA - 

ENTIDADE = TABELA 
CAMPOS = ATRIBUTOS

*/

CLIENTE

NOME - CARACTER(30)
CPF - NUMERICO(11)
EMAIL - CARACTER(30)
TELEFONE - CARACTER(30)
ENDERECO - CARACTER(100)
SEXO - CARACTER(1)

/* PROCESSOS DE MODELAGEM */

/* FASE 01 E FASE 02 - ADM DE DADOS */

MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM

/* FASE 03 - DBA / AD */

MODELAGEM FÍSICA - SCRIPTS DE BANCO 

/* INICIANDO A MODELAGEM FÍSICA */

/* CRIANDO O BANCO DE DADOS */

CREATE DATABASE EXEMPLO

CREATE DATABASE PROJETO;

/* CONECTANDO-SE AO BANCO */

USE PROJETO;

/* CRIANDO A TABLA DO CLIENTES */

CREATE TABLE CLIENTE (
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
);

/* VERIFICANDO AS TABELAS DO BANCO DE DADOS */

SHOW TABLES;

/* DESCOBRINDO COMO É A ESTRUTURA DE UMA TABELA */

DESC CLIENTE;

/* SINTAXE BÁSICA DE INSERÇÃO - INSERT INTO TABELA... */

/* FORMA 01 - OMITINDO AS COLUNAS */

INSERT INTO CLIENTE VALUES('JHONATAN','M','JHONY@GMAIL.COM',988633441,'16999333990','RUA MAIA - RIBEIRAO PRETO - SP');

/* FORMA 02 - DESCREVENDO AS COLUNAS */

INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('THIAGO','M','RUA TACO - RIBEIRAO PRETO - SP','16999333944', 988633455);

/* FORMA 03 - INSERT COMPACTO - SOMENTE MYSQL */

INSERT INTO CLIENTE VALUE('WELL','M','WELL@GMAIL.COM',228633441,'16999733990','RUA MARIO - RIBEIRAO PRETO - SP'),
						 ('DANIEL','M','DANI@GMAIL.COM',988563441,'16999833990','RUA EUCLIDES - RIBEIRAO PRETO - SP'),
						 ('MANUELA','F','MANU@GMAIL.COM',863344112,'16999339493','RUA JOÃO - RIBEIRAO PRETO - SP'),
						 ('MATHEUS','M','MATHEUS@GMAIL.COM',812344112,'16900339493','RUA ORION - SERTÃOZINHO - SP'),
						 ('LETICIA','F','LETICIA@GMAIL.COM',835344112,'16919330493','RUA JOÃO - RIBEIRAO PRETO - SP'),
						 ('JOSY','F','JOSY@GMAIL.COM',863347212,'16592332493','RUA ITAPIRU - SERTÃOZINHO - SP'),
						 ('EDUARDO','M','MANU@GMAIL.COM',869244112,'11789329493','RUA ITAPIRU - RIO DE JANEIRO - RJ'),
						 ('DANIELA','F','DANIELA@GMAIL.COM',863294112,'11789329493','RUA ITAPIRU - RIO DE JANEIRO - RJ');
						 
						 
						 
/* ERROR - Out of range value for column 'CPF' at row 1 */						 

INSERT INTO CLIENTE VALUES('LARISSA','F','LARI@GMAIL.COM',98863344112,'16999339490','RUA MAIA - RIBEIRAO PRETO - SP');

/* O COMANDO SELECT - SELEÇÃO, 'PROJEÇÃO' E JUNÇÃO */

SELECT NOW();

SELECT NOW() AS DATA_HORA;

SELECT NOW() AS DATA_HORA, 'JHONATAN' AS ALUNO;

SELECT 'JHONATAN';

SELECT 'BANCO DE DADOS';

/* ALIAS DE COLUNAS */

SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;

SELECT EMAIL, SEXO, ENDERECO, NOME FROM CLIENTE;

SELECT EMAIL, SEXO, ENDERECO, NOME, NOW() AS DATA_HORA FROM CLIENTE;

/* APENAS PARA FINS ACADEMICOS */

SELECT * FROM CLIENTE;

/* FILTRANDO DADOS COM WHERE E LIKE */

SELECT NOME, TELEFONE FROM CLIENTE;

/* FILTRANDO */

SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME, ENDERECO FROM CLIENTE
WHERE SEXO = 'F';

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO = 'SP'; /* EMPTY SET - CONJUNTO VAZIO */
/* ENDERECO NÃO É IGUAL A SP, PARA DADOS DE APROXIMAÇÃO UTILIZAR LIKE */

/* UTILIZANDO O LIKE */

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE 'SP'; /* EMPTY SET - CONJUNTO VAZIO */

/* CARACTER CORINGA % -> QUALQUER COISA */

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE '%SP'; /* QUALQUER COISA COM FINAL SP */

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE '%SP';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE 'RUA MAIA%'; /*COMEÇA COM RUA MAIA COM FINAL QUALQUER COISA */

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE '%RIBEIRAO PRETO%'; /* QUALQUER COISA RIBEIRAO PRETO QUALQUER COISA */

/* OPERADORES LÓGICOS 
OR -> PARA QUE A SAIDA SEJA VERDADEIRA, BASTA QUE APENAS UMA CONDICAO SEJA VERDADEIRA
AND -> PARA QUE A SAIDA SEJA VERDADEIRA, TODAS AS CONDICOES PRECISAM SER VERDADEIRAS
*/

/*
Os operadores OR e AND  são aplamente utilizados com LIKE e %. Contudo, devemos nos atentar a performance!
*/

/* OR - OU */

SHOW DATABASE;

USE PROJETO;

SELECT * FROM CLIENTE;

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE SEXO = 'M' OR ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE SEXO = 'F' OR ENDERECO LIKE '%MG';

/* AND - E */

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE SEXO = 'M' AND ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE SEXO = 'F' AND ENDERECO LIKE '%MG';